version: '3'
services:
  metapulse-inference-server:
    build: .
    image: metapulse-inference-image
    mem_limit: 4g
    mem_reservation: 256m
    memswap_limit: 10g
    volumes:
      - .:/workspace:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]