version: '3'
services:
  metapulse-inference-server:
    build: .
    image: metapulse-inference-image
    ports:
      - 7070:8080
    volumes:
      - .:/workspace:cached
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: /bin/bash -c "cd /workspace && python ./app/server.py"
